---

- name: Install python-passlib
  package:
    name: python-passlib

- name: "Add {{ BASIC_AUTH_USER }} to {{ container_storage_dir_base }}/nginx/htpasswd/{{ VIRTUAL_HOST }}"
  htpasswd:
    path: "{{ container_storage_dir_base }}/nginx/htpasswd/{{ VIRTUAL_HOST }}"
    name: "{{ BASIC_AUTH_USER }}"
    password: "{{ BASIC_AUTH_PASSWD }}"
